name: Production Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: build
      cancel-in-progress: false
    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/checkout@v3
        with:
          repository: 66Leo66/blog.6leo6.com
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install
      - run: yarn build
      # - run: ls

      - name: Deploy
        id: deploy
        uses: 66Leo66/push-to-vercel@v5
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-projectId: ${{ secrets.VERCEL_PROJECTID }}
          vercel-orgId: ${{ secrets.VERCEL_ORGID }}
          production: 'true'
          dir: 'dist'
          # vercel-region: 'hkg1'
