name: Production Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  hugo-blog:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment:
      name: production
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: '0'
          submodules: 'true'
          repository: 66Leo66/blog.6leo6.com
          token: ${{ secrets.PAT }}
      
      - name: Correct Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
      
      - name: Generate
        uses: 66Leo66/build-hugo-blog@v2

      - name: Deploy
        id: deploy
        uses: 66Leo66/push-to-vercel@v5
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-projectId: ${{ secrets.VERCEL_PROJECTID }}
          vercel-orgId: ${{ secrets.VERCEL_ORGID }}
          production: 'true'
          # vercel-region: 'hkg1'